mysql:
  datasource:
    dev:
      url: jdbc:mysql://192.168.11.113:30022/hc_opdchis_center?autoReconnect=true&useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull
      username: sqldubbo
      password: EAteGvRHN^Z5@hQ
      minPoolSize: 3
      maxPoolSize: 25
      maxLifetime: 20000
      borrowConnectionTimeout: 30
      loginTimeout: 30
      maintenanceInterval: 60
      maxIdleTime: 60
      testQuery: select 1
    online:
      url: jdbc:mysql://192.168.11.113:30022/hc_opdchis_center?autoReconnect=true&useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull
      username: sqldubbo
      password: EAteGvRHN^Z5@hQ
      minPoolSize: 3
      maxPoolSize: 25
      maxLifetime: 20000
      borrowConnectionTimeout: 30
      loginTimeout: 30
      maintenanceInterval: 60
      maxIdleTime: 60
      testQuery: select 1

logging:
  level:
    org:
      hibernate:
        type:
          descriptor:
            sql:
              BasicBinder: info
