spring:
  datasource:
    url: jdbc:mysql://192.168.11.113:30022/hc_opdchis_center?autoReconnect=true&useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull
    username: sqldubbo
    password: EAteGvRHN^Z5@hQ